/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CircuitoDAO;
import Controller.JDBCUtil;
import Model.Circuito;
import javax.swing.JOptionPane;

/**
 *
 * @author luizg
 */
public class VwCircuito extends javax.swing.JFrame {

    int index = 0;
    CircuitoDAO ctrl = new CircuitoDAO();

    /**
     * Creates new form VwCircuito
     */
    public VwCircuito() {
        initComponents();
        ctrl.CriaConexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPista = new javax.swing.JLabel();
        jLabelPais = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jLabelExt = new javax.swing.JLabel();
        jLabelVoltas = new javax.swing.JLabel();
        jLabelRcrd = new javax.swing.JLabel();
        jTextFieldPista = new javax.swing.JTextField();
        jTextFieldPais = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jTextFieldExt = new javax.swing.JTextField();
        jTextFieldVoltas = new javax.swing.JTextField();
        jTextFieldRcrd = new javax.swing.JTextField();
        jLabelTitle = new javax.swing.JLabel();
        jLabelKm = new javax.swing.JLabel();
        jButtonAbrir = new javax.swing.JButton();
        jButtonAnt = new javax.swing.JButton();
        jButtonProx = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jTextFieldId = new javax.swing.JTextField();
        jButtonBusca = new javax.swing.JButton();
        jLabelId = new javax.swing.JLabel();
        jButtonDel = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Circuito");

        jLabelPista.setText("Nome do Circuito:");

        jLabelPais.setText("País:");

        jLabelCidade.setText("Cidade:");

        jLabelExt.setText("Extensão:");

        jLabelVoltas.setText("Número de Voltas:");

        jLabelRcrd.setText("Tempo Record:");

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitle.setText("CIRCUITO");

        jLabelKm.setText("Km.");

        jButtonAbrir.setText("Abrir");
        jButtonAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAbrirMouseClicked(evt);
            }
        });

        jButtonAnt.setText("Anterior");
        jButtonAnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAntMouseClicked(evt);
            }
        });

        jButtonProx.setText("Próximo");
        jButtonProx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonProxMouseClicked(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalvarMouseClicked(evt);
            }
        });

        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });

        jButtonBusca.setText("Buscar por Id");
        jButtonBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBuscaMouseClicked(evt);
            }
        });

        jLabelId.setText("Id:");

        jButtonDel.setText("Deletar por Id");
        jButtonDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDelMouseClicked(evt);
            }
        });

        jButtonEdit.setText("Editar por Id");
        jButtonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelRcrd)
                                        .addComponent(jLabelPais)
                                        .addComponent(jLabelCidade)
                                        .addComponent(jLabelExt)
                                        .addComponent(jLabelVoltas))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldPais)
                                        .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextFieldExt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabelKm))
                                        .addComponent(jTextFieldVoltas, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldRcrd, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelPista)
                                        .addComponent(jLabelId))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldPista))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAbrir)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAnt)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonProx)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSalvar)))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonEdit)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDel)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBusca)
                        .addGap(23, 23, 23))))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabelTitle)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelId))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPista, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldPista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPais)
                    .addComponent(jTextFieldPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCidade, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelExt)
                    .addComponent(jLabelKm))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVoltas)
                    .addComponent(jTextFieldVoltas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRcrd)
                    .addComponent(jTextFieldRcrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonDel)
                    .addComponent(jButtonBusca))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAbrir)
                    .addComponent(jButtonAnt)
                    .addComponent(jButtonProx)
                    .addComponent(jButtonSalvar))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalvarMouseClicked
        // TODO add your handling code here:
        Circuito circ = MontaCircuito();
        circ.setId(ctrl.getUltimoId() + 1);
        if (ctrl.Inserir(circ)) {
            JOptionPane.showMessageDialog(this, "Circuito inserido com sucesso.");
            jButtonAbrirMouseClicked(evt);
            if (JDBCUtil.MovUltimo(ctrl.getRsdados())) {
                Nav(ctrl.getCircuito());
            } else {
                JOptionPane.showMessageDialog(this, "O ultimo registro ja esta selecionado.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao inserir cliente.");
        }
    }//GEN-LAST:event_jButtonSalvarMouseClicked

    private void jButtonAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAbrirMouseClicked
        // TODO add your handling code here:
        if (ctrl.CriaConexao()) {
            if (ctrl.ConsultarTodos()) {
                if (JDBCUtil.MovPrimeiro(ctrl.getRsdados())) {
                    Circuito circuito = ctrl.getCircuito();
                    if (circuito != null) {
                        Nav(circuito);
                    } else {
                        JOptionPane.showMessageDialog(this, "Circuito retornado é nulo.");
                        LimpaCampos();
                    }
                }
            }
        }
    }//GEN-LAST:event_jButtonAbrirMouseClicked

    private void jButtonProxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonProxMouseClicked
        // TODO add your handling code here:
        try {
            if (JDBCUtil.MovProximo(ctrl.getRsdados())) {
                Nav(ctrl.getCircuito());
            } else {
                JOptionPane.showMessageDialog(this, "Nao existe proximo elemento.");
            }
        } catch (NullPointerException erro) {
            JOptionPane.showMessageDialog(this, "Nao existe proximo elemento.");
        }
    }//GEN-LAST:event_jButtonProxMouseClicked

    private void jButtonAntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAntMouseClicked
        // TODO add your handling code here:
        try {
            if (JDBCUtil.MovAnterior(ctrl.getRsdados())) {
                Nav(ctrl.getCircuito());
            } else {
                JOptionPane.showMessageDialog(this, "Nao existe registro anterior.");
            }
        } catch (NullPointerException erro) {
            JOptionPane.showMessageDialog(this, "Nao existe registro anterior.");
        }
    }//GEN-LAST:event_jButtonAntMouseClicked

    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdActionPerformed

    private void jButtonBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscaMouseClicked
        // TODO add your handling code here:
        try {
            int aux = Integer.parseInt(jTextFieldId.getText());
            Circuito circuito = ctrl.getCircuitoPorId(aux);
            if (circuito == null) {
                JOptionPane.showMessageDialog(this, "Informe um numero valido");
                return;
            }
            Nav(circuito);
        } catch (NumberFormatException erro) {
            System.out.println(erro);
            JOptionPane.showMessageDialog(this, "Informe um numero valido");
        }
    }//GEN-LAST:event_jButtonBuscaMouseClicked

    private void jButtonDelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDelMouseClicked
        // TODO add your handling code here:
        try {
            Circuito circ = MontaCircuito();
            if (ctrl.Excluir(circ)) {
                JOptionPane.showMessageDialog(this, "Circuito excluído com sucesso. \nReiniciando a navegacao.");
                jButtonAbrirMouseClicked(evt);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir circuito.");
            }
        } catch (NumberFormatException erro) {
            System.out.println(erro);
            JOptionPane.showMessageDialog(this, "Informe um ID valido.");
        }
    }//GEN-LAST:event_jButtonDelMouseClicked

    private void jButtonEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditMouseClicked
        // TODO add your handling code here:
        Circuito circ = MontaCircuito();
        int temp = circ.getId();
        if (ctrl.Alterar(circ)) {
            JOptionPane.showMessageDialog(this, "Circuito alterado com sucesso.");
            jButtonAbrirMouseClicked(evt);
            Buscar(temp);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao alterar cliente.");
        }

    }//GEN-LAST:event_jButtonEditMouseClicked

    public void Nav(Circuito circ) {
        jTextFieldPista.setText(circ.getPista());
        jTextFieldPais.setText(circ.getPais());
        jTextFieldCidade.setText(circ.getCidade());
        jTextFieldExt.setText(String.valueOf(circ.getExtensao()));
        jTextFieldVoltas.setText(String.valueOf(circ.getVoltas()));
        jTextFieldRcrd.setText(circ.getRecord());
        jTextFieldId.setText(String.valueOf(circ.getId()));
    }

    public void Buscar(int index) {
        Circuito circuito = ctrl.getCircuitoPorId(index);
        Nav(circuito);
    }

    public Circuito MontaCircuito() {
        Circuito circ = null;
        int temp;
        if (jTextFieldId.getText().equals("")) {
            temp = 0;
            System.out.println("id virou 0");
        } else {
            temp = Integer.valueOf(jTextFieldId.getText());
            System.out.println("id virou: " + temp);
        }
        int id = temp;
        String pista = jTextFieldPista.getText();
        String pais = jTextFieldPais.getText();
        String cidade = jTextFieldCidade.getText();
        int extensao = Integer.valueOf(jTextFieldExt.getText());
        int voltas = Integer.valueOf(jTextFieldVoltas.getText());
        String record = jTextFieldRcrd.getText();
        circ = new Circuito(id, pista, pais, cidade, extensao, voltas, record);
        return circ;
    }
    
    public void LimpaCampos(){
        jTextFieldPista.setText("");
        jTextFieldPais.setText("");
        jTextFieldCidade.setText("");
        jTextFieldExt.setText("");
        jTextFieldVoltas.setText("");
        jTextFieldRcrd.setText("");
        jTextFieldId.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VwCircuito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VwCircuito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VwCircuito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VwCircuito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VwCircuito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrir;
    private javax.swing.JButton jButtonAnt;
    private javax.swing.JButton jButtonBusca;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonProx;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelExt;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelKm;
    private javax.swing.JLabel jLabelPais;
    private javax.swing.JLabel jLabelPista;
    private javax.swing.JLabel jLabelRcrd;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelVoltas;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldExt;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldPais;
    private javax.swing.JTextField jTextFieldPista;
    private javax.swing.JTextField jTextFieldRcrd;
    private javax.swing.JTextField jTextFieldVoltas;
    // End of variables declaration//GEN-END:variables
}
