/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControleRelatorios;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author luizg
 */
public class VwControleRelatorio extends javax.swing.JFrame {

    ControleRelatorios controle = new ControleRelatorios();
    /**
     * Creates new form VwControleRelatorio
     */
    public VwControleRelatorio() {
        initComponents();
    }
    
    private Map constroiParametrosPiloto() {
        Map params = new HashMap();
        String max = JOptionPane.showInputDialog(
                this,
                "Digite a equipe para o relatório",
                "Entrada de dados",
                JOptionPane.QUESTION_MESSAGE);

        params.put("P1", max);
        return params;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btVwPil = new javax.swing.JButton();
        btVwPilPdf = new javax.swing.JButton();
        btVwPilNac = new javax.swing.JButton();
        btVwPilNacPdf = new javax.swing.JButton();
        btVwPntsEq = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatorios");

        btVwPil.setText("Visualiza Relatorio de Pilotos");
        btVwPil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVwPilMouseClicked(evt);
            }
        });

        btVwPilPdf.setText("Salva Relatorio de Pilotos em PDF");
        btVwPilPdf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVwPilPdfMouseClicked(evt);
            }
        });

        btVwPilNac.setText("Visualiza Relatorio de Pilotos por Nacionalidade");
        btVwPilNac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVwPilNacMouseClicked(evt);
            }
        });

        btVwPilNacPdf.setText("Salva Relatorio de Pilotos por Nacionalidade em PDF");
        btVwPilNacPdf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVwPilNacPdfMouseClicked(evt);
            }
        });

        btVwPntsEq.setText("Visualiza Relatorio de Pontuação de Equipes");
        btVwPntsEq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVwPntsEqMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btVwPntsEq, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVwPilNacPdf)
                    .addComponent(btVwPilNac, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVwPilPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVwPil, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btVwPil)
                .addGap(18, 18, 18)
                .addComponent(btVwPilPdf)
                .addGap(18, 18, 18)
                .addComponent(btVwPilNac)
                .addGap(18, 18, 18)
                .addComponent(btVwPilNacPdf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btVwPntsEq)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btVwPilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVwPilMouseClicked
        // TODO add your handling code here:
        controle.RelatorioPiloto(true);
    }//GEN-LAST:event_btVwPilMouseClicked

    private void btVwPilPdfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVwPilPdfMouseClicked
        // TODO add your handling code here:
        controle.RelatorioPiloto(false);
    }//GEN-LAST:event_btVwPilPdfMouseClicked

    private void btVwPilNacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVwPilNacMouseClicked
        // TODO add your handling code here:
        controle.RelatorioPilotoParametro(constroiParametrosPiloto(), true);
    }//GEN-LAST:event_btVwPilNacMouseClicked

    private void btVwPilNacPdfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVwPilNacPdfMouseClicked
        // TODO add your handling code here:
        controle.RelatorioPilotoParametro(constroiParametrosPiloto(), false);
    }//GEN-LAST:event_btVwPilNacPdfMouseClicked

    private void btVwPntsEqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVwPntsEqMouseClicked
        // TODO add your handling code here:
        controle.RelatorioPontos();
    }//GEN-LAST:event_btVwPntsEqMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VwControleRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VwControleRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VwControleRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VwControleRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VwControleRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVwPil;
    private javax.swing.JButton btVwPilNac;
    private javax.swing.JButton btVwPilNacPdf;
    private javax.swing.JButton btVwPilPdf;
    private javax.swing.JButton btVwPntsEq;
    // End of variables declaration//GEN-END:variables
}
