/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.JDBCUtil;
import Controller.PilotoDAO;
import Model.Piloto;
import javax.swing.JOptionPane;

/**
 *
 * @author luizg
 */
public class VwPiloto extends javax.swing.JFrame {

    int index = 0;
    PilotoDAO ctrl = new PilotoDAO();

    /**
     * Creates new form VwPiloto
     */
    public VwPiloto() {
        initComponents();
        ctrl.CriaConexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelPiloto = new javax.swing.JLabel();
        jLabelNac = new javax.swing.JLabel();
        jLabelEquipe = new javax.swing.JLabel();
        jLabelNum = new javax.swing.JLabel();
        jLabelPts = new javax.swing.JLabel();
        jTextFieldPiloto = new javax.swing.JTextField();
        jTextFieldNac = new javax.swing.JTextField();
        jTextFieldEquipe = new javax.swing.JTextField();
        jTextFieldNum = new javax.swing.JTextField();
        jTextFieldPts = new javax.swing.JTextField();
        jButtonAbrir = new javax.swing.JButton();
        jButtonAnt = new javax.swing.JButton();
        jButtonProx = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jLabelId = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jButtonBusca = new javax.swing.JButton();
        jButtonDel = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Piloto");

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitle.setText("PILOTO");

        jLabelPiloto.setText("Nome do Piloto:");

        jLabelNac.setText("Nacionalidade:");

        jLabelEquipe.setText("Equipe:");

        jLabelNum.setText("Número:");

        jLabelPts.setText("Pontos:");

        jTextFieldPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPilotoActionPerformed(evt);
            }
        });

        jButtonAbrir.setText("Abrir");
        jButtonAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAbrirMouseClicked(evt);
            }
        });
        jButtonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirActionPerformed(evt);
            }
        });

        jButtonAnt.setText("Anterior");
        jButtonAnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAntMouseClicked(evt);
            }
        });

        jButtonProx.setText("Próximo");
        jButtonProx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonProxMouseClicked(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalvarMouseClicked(evt);
            }
        });

        jLabelId.setText("Id:");

        jButtonBusca.setText("Buscar por Id");
        jButtonBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBuscaMouseClicked(evt);
            }
        });

        jButtonDel.setText("Deletar por Id");
        jButtonDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDelMouseClicked(evt);
            }
        });

        jButtonEdit.setText("Editar por Id");
        jButtonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditMouseClicked(evt);
            }
        });
        jButtonEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonEditKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonAbrir)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonAnt)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonProx)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonSalvar))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jButtonEdit)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonDel)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonBusca)
                                    .addGap(8, 8, 8)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelNac)
                                    .addComponent(jLabelPiloto)
                                    .addComponent(jLabelEquipe)
                                    .addComponent(jLabelNum)
                                    .addComponent(jLabelPts)
                                    .addComponent(jLabelId))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldPiloto)
                                    .addComponent(jTextFieldNac)
                                    .addComponent(jTextFieldEquipe, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(jTextFieldPts, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabelTitle)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelId, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPiloto)
                    .addComponent(jTextFieldPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNac)
                    .addComponent(jTextFieldNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEquipe)
                    .addComponent(jTextFieldEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNum)
                    .addComponent(jTextFieldNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPts)
                    .addComponent(jTextFieldPts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonDel)
                    .addComponent(jButtonBusca))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAbrir)
                    .addComponent(jButtonAnt)
                    .addComponent(jButtonProx)
                    .addComponent(jButtonSalvar))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPilotoActionPerformed

    private void jButtonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAbrirActionPerformed

    private void jButtonSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalvarMouseClicked
        // TODO add your handling code here:
        Piloto pil = MontaPiloto();
        pil.setId(ctrl.getUltimoId() + 1);
        if (ctrl.Inserir(pil)) {
            JOptionPane.showMessageDialog(this, "Piloto inserido com sucesso.");
            jButtonAbrirMouseClicked(evt);
            if (JDBCUtil.MovUltimo(ctrl.getRsdados())) {
                Nav(ctrl.getPiloto());
            } else {
                JOptionPane.showMessageDialog(this, "O ultimo registro ja esta selecionado.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao inserir piloto.");
        }
    }//GEN-LAST:event_jButtonSalvarMouseClicked

    private void jButtonAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAbrirMouseClicked
        // TODO add your handling code here:
        if (ctrl.CriaConexao()) {
            if (ctrl.ConsultarTodos()) {
                if (JDBCUtil.MovPrimeiro(ctrl.getRsdados())) {
                    Piloto piloto = ctrl.getPiloto();
                    if (piloto != null) {
                        Nav(piloto);
                    } else {
                        JOptionPane.showMessageDialog(this, "Piloto retornado é nulo.");
                        LimpaCampos();
                    }
                }
            }
        }
    }//GEN-LAST:event_jButtonAbrirMouseClicked

    private void jButtonProxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonProxMouseClicked
        // TODO add your handling code here:        
        try {
            if (JDBCUtil.MovProximo(ctrl.getRsdados())) {
                Nav(ctrl.getPiloto());
            } else {
                JOptionPane.showMessageDialog(this, "Nao existe proximo elemento.");
            }
        } catch (NullPointerException erro) {
            JOptionPane.showMessageDialog(this, "Nao existe proximo elemento.");
        }
    }//GEN-LAST:event_jButtonProxMouseClicked

    private void jButtonAntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAntMouseClicked
        // TODO add your handling code here:
        try {
            if (JDBCUtil.MovAnterior(ctrl.getRsdados())) {
                Nav(ctrl.getPiloto());
            } else {
                JOptionPane.showMessageDialog(this, "Nao existe registro anterior.");
            }
        } catch (NullPointerException erro) {
            JOptionPane.showMessageDialog(this, "Nao existe registro anterior.");
        }
    }//GEN-LAST:event_jButtonAntMouseClicked

    private void jButtonBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscaMouseClicked
        // TODO add your handling code here
        try {
            int aux = Integer.parseInt(jTextFieldId.getText());
            Piloto piloto = ctrl.getPilotoPorId(aux);
            if (piloto == null) {
                JOptionPane.showMessageDialog(this, "Informe um numero valido");
                return;
            }
            Nav(piloto);
        } catch (NumberFormatException erro) {
            System.out.println(erro);
            JOptionPane.showMessageDialog(this, "Informe um numero valido");
        }
    }//GEN-LAST:event_jButtonBuscaMouseClicked

    private void jButtonDelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDelMouseClicked
        // TODO add your handling code here:
        try {
            Piloto pil = MontaPiloto();
            System.out.println("Piloto: " + pil.getId() + pil.getNome() + pil.getEquipe());
            System.out.println("Id: " + pil.getId());
            if (ctrl.Excluir(pil)) {
                JOptionPane.showMessageDialog(this, "Piloto excluido com sucesso. \nReiniciando a navegacao.");
                jButtonAbrirMouseClicked(evt);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir piloto.");
            }
        } catch (NumberFormatException erro) {
            System.out.println(erro);
            JOptionPane.showMessageDialog(this, "Informe um ID valido.");
        }
    }//GEN-LAST:event_jButtonDelMouseClicked

    private void jButtonEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonEditKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditKeyPressed

    private void jButtonEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditMouseClicked
        // TODO add your handling code here:
        Piloto pil = MontaPiloto();
        int temp = pil.getId();
        if (ctrl.Alterar(pil)) {
            JOptionPane.showMessageDialog(this, "Piloto alterado com sucesso.");
            jButtonAbrirMouseClicked(evt);
            Buscar(temp);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao alterar piloto.");
        }
    }//GEN-LAST:event_jButtonEditMouseClicked

    public void Nav(Piloto piloto) {
        jTextFieldPiloto.setText(piloto.getNome());
        jTextFieldNac.setText(piloto.getNacionalidade());
        jTextFieldEquipe.setText(piloto.getEquipe());
        jTextFieldNum.setText(String.valueOf(piloto.getNumero()));
        jTextFieldPts.setText(String.valueOf(piloto.getPontos()));
        jTextFieldId.setText(String.valueOf(piloto.getId()));
    }

    public void Buscar(int index) {
        Piloto piloto = ctrl.getPilotoPorId(index);
        Nav(piloto);
    }

    public Piloto MontaPiloto() {
        Piloto pil = null;
        int temp;
        if (jTextFieldId.getText().equals("")) {
            temp = 0;
            System.out.println("id virou 0");
        } else {
            temp = Integer.valueOf(jTextFieldId.getText());
            System.out.println("id virou: " + temp);
        }
        int id = temp;
        String nome = jTextFieldPiloto.getText();
        String nacionalidade = jTextFieldNac.getText();
        String equipe = jTextFieldEquipe.getText();
        int numero = Integer.valueOf(jTextFieldNum.getText());
        int pontos = Integer.valueOf(jTextFieldPts.getText());
        pil = new Piloto(id, nome, nacionalidade, equipe, numero, pontos);
        return pil;
    }

    public void LimpaCampos() {
        jTextFieldId.setText("");
        jTextFieldPiloto.setText("");
        jTextFieldNac.setText("");
        jTextFieldEquipe.setText("");
        jTextFieldNum.setText("");
        jTextFieldPts.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VwPiloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VwPiloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VwPiloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VwPiloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VwPiloto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrir;
    private javax.swing.JButton jButtonAnt;
    private javax.swing.JButton jButtonBusca;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonProx;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelEquipe;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelNac;
    private javax.swing.JLabel jLabelNum;
    private javax.swing.JLabel jLabelPiloto;
    private javax.swing.JLabel jLabelPts;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JTextField jTextFieldEquipe;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNac;
    private javax.swing.JTextField jTextFieldNum;
    private javax.swing.JTextField jTextFieldPiloto;
    private javax.swing.JTextField jTextFieldPts;
    // End of variables declaration//GEN-END:variables
}
